name = "shenbypass"
main = "src/wizard.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_PASSWORD = "shen_admin_2026"
WIZARD_DOMAIN = "shenbypass.workers.dev"

[[kv_namespaces]]
binding = "POOL"
id = "placeholder_kv_id"
