name = "shenbypass"
main = "src/wizard.js"
compatibility_date = "2026-09-16"
compatibility_flags = []

# ─── D1 Database ───
[[d1_databases]]
binding = "My-database"
database_id = "49ea6a9e-176b-4979-9e51-a9f2c45babb4"

# ─── Service Binding: My-kv ───
[[services]]
binding = "My-kv"
service = "shenbypass"
environment = "production"

# ─── Service Binding: POOL ───
[[services]]
binding = "POOL"
service = "shenbypass"
environment = "production"
